use tempdb;

CREATE TABLE T_TOPIC( id int IDENTITY(1,1) PRIMARY KEY, USER_ID 		VARCHAR(32) 	NOT NULL, TOPIC_TYPE 	VARCHAR(4) 	NOT NULL, TOPIC_ID 		VARCHAR(256)	NOT NULL, REGISTER_DATE 	VARCHAR(14), ACTIVE VARCHAR(1) NOT NULL, unique(USER_ID,TOPIC_TYPE,TOPIC_ID));
CREATE TABLE T_MESSAGE (  MESSAGE_ID 	VARCHAR(40)	NOT NULL, TOPIC_TYPE 	VARCHAR(4)		NOT NULL, TOPIC_ID 		VARCHAR(256)	NOT NULL, MESSAGE_BODY 	VARCHAR(4000)	NOT NULL, REGISTER_DATE 	VARCHAR(14), EXPIRATION_DATE 	VARCHAR(14), PRIMARY KEY (MESSAGE_ID));
CREATE TABLE T_USER_MESSAGE (id int IDENTITY(1,1) PRIMARY KEY,  USER_ID 		VARCHAR(32)	NOT NULL, MESSAGE_ID 	VARCHAR(40)	NOT NULL, MESSAGE_STATE 	VARCHAR(1)		NOT NULL, CHECK_DATE 	VARCHAR(14));
CREATE INDEX IDX_USER_MESSAGE On T_USER_MESSAGE (USER_ID,MESSAGE_ID);
CREATE TABLE T_MOBILE(id int IDENTITY(1,1) PRIMARY KEY,USER_ID     VARCHAR(32)   NOT NULL, DEVICE_TOKEN   VARCHAR(256)  NOT NULL, OS          VARCHAR(1)    NOT NULL, OS_VERSION  VARCHAR(20), REGISTER  VARCHAR(1), ACTIVE      VARCHAR(1),unique(USER_ID, DEVICE_TOKEN));
CREATE TABLE T_NOTIFICATION(id int IDENTITY(1,1) PRIMARY KEY,MESSAGE_ID  VARCHAR(40)    NOT NULL, DEVICE_TOKEN   VARCHAR(256)   NOT NULL, TOPIC_TYPE  VARCHAR(4)     NOT NULL, TOPIC_ID    VARCHAR(256), MESSAGE     VARCHAR(4000), CHECK_DATE        VARCHAR(14), RESULT      VARCHAR(1), ERROR_CODE  VARCHAR(30), unique(MESSAGE_ID, DEVICE_TOKEN));



